#!/usr/bin/env python3
"""Tests for the pandoc reference document that renders the master CV.

Two layers:

1. **Structure.** The shipped ``assets/reference.docx`` -- and a fresh one
   regenerated by ``scripts/make-reference-docx.py`` with whatever pandoc is
   installed -- must carry the metrics the CV phase relies on: half-inch
   margins *inside* ``sectPr``, a pinned page size, no coloured styles, a single
   10pt document default, and the per-style sizes. Needs only ``pandoc`` (for
   the regeneration case).

2. **Render.** The fixture CV in ``tests/fixtures/cv-fixture.md`` (~6,500
   characters, the size of a real two-page master) is pushed through the exact
   pipeline ``references/02-master-cv.md`` prescribes -- pandoc -> .docx ->
   LibreOffice -> .pdf -> pdfinfo/pdftotext -- and must land on two pages with
   its text intact, its margins measurably at half an inch and not one chromatic
   pixel on the page (Harvard style is black and white). As a control,
   the same CV without the reference document must NOT fit, which is the whole
   reason the asset exists. Needs ``pandoc``, ``libreoffice`` and poppler
   (``pdfinfo``, ``pdftotext``, ``pdftoppm``); skipped when they are missing
   unless ``CI`` is set, in which case missing tools fail the run.

Run:  python3 tests/test_reference_docx.py      (or: pytest tests/)
"""

from __future__ import annotations

import importlib.util
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import traceback
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILL = ROOT / "skills" / "fix-cv-find-job-skill"
SHIPPED = SKILL / "assets" / "reference.docx"
FIXTURE = ROOT / "tests" / "fixtures" / "cv-fixture.md"
SCRIPT = ROOT / "scripts" / "make-reference-docx.py"

_spec = importlib.util.spec_from_file_location("make_reference_docx", SCRIPT)
mk = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(mk)

MAX_PAGES = 2               # the gate in references/02-master-cv.md
MIN_TEXT_CHARS = 5000       # "a PDF that yields almost no characters is an image"
HALF_INCH_PT = 36.0
MUST_SURVIVE = (            # spot-check from the reference file: contact, employers, metrics
    "maria.fernandez@example.com",
    "+54 11 5555 0000",
    "Acme Logistics S.A.",
    "Supermercados Sol",
    "31%",
    "USD 210k/yr",
)


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #

def _need(*tools: str) -> None:
    missing = [t for t in tools if shutil.which(t) is None]
    if not missing:
        return
    msg = "missing tools: %s (apt: pandoc libreoffice-writer poppler-utils)" % ", ".join(missing)
    if os.environ.get("CI"):
        raise AssertionError(msg)
    raise unittest.SkipTest(msg)


def _assert_structure(report: dict, label: str) -> None:
    assert not report["problems"], "%s is not usable:\n  - %s" % (label, "\n  - ".join(report["problems"]))
    assert report["pgSz"] in ({"w": w, "h": h} for w, h in mk.PAGE_SIZES.values()), \
        "%s: pgSz %r is not one of the known page sizes" % (label, report["pgSz"])
    assert report["coloured_styles"] == [], \
        "%s: Harvard style is black and white, but these styles carry a colour: %s" % (label, report["coloured_styles"])


def _render(md: pathlib.Path, workdir: pathlib.Path, reference: pathlib.Path | None) -> dict:
    """markdown -> docx -> pdf, exactly as the skill instructs; return what the gate reads."""
    docx = workdir / ("with-ref.docx" if reference else "stock.docx")
    cmd = ["pandoc", str(md), "-o", str(docx)]
    if reference:
        cmd += ["--reference-doc=%s" % reference]
    subprocess.run(cmd, check=True)

    # A private profile dir keeps LibreOffice from tripping over a running
    # instance or a locked default profile (the usual reason it hangs in CI).
    profile = workdir / "lo-profile"
    subprocess.run(
        ["libreoffice", "--headless", "-env:UserInstallation=file://%s" % profile,
         "--convert-to", "pdf", str(docx), "--outdir", str(workdir)],
        check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=180,
    )
    pdf = docx.with_suffix(".pdf")
    assert pdf.exists(), "LibreOffice produced no PDF for %s" % docx.name

    info = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True, check=True).stdout
    pages = int(re.search(r"^Pages:\s+(\d+)", info, re.M).group(1))
    text = subprocess.run(["pdftotext", str(pdf), "-"], capture_output=True, text=True, check=True).stdout
    bbox = subprocess.run(["pdftotext", "-bbox-layout", "-f", "1", "-l", "1", str(pdf), "-"],
                          capture_output=True, text=True, check=True).stdout
    xs = [float(x) for x in re.findall(r'<line xMin="([\d.]+)"', bbox)]
    return {"pages": pages, "text": text, "left_margin_pt": min(xs) if xs else None, "pdf": pdf}


def _chromatic_pixels(pdf: pathlib.Path, workdir: pathlib.Path, page: int = 1, threshold: int = 30) -> tuple[int, int]:
    """Rasterize one page and count pixels whose channels differ by more than
    ``threshold`` -- i.e. anything that is not black, white or grey.

    Uses pdftoppm's default PPM (P6) output, parsed by hand so the test needs no
    imaging library. Text anti-aliasing is greyscale, so a black-and-white page
    scores zero; pandoc's blue headings score in the thousands at 60 dpi.
    """
    stem = workdir / ("raster-%s" % pdf.stem)
    subprocess.run(["pdftoppm", "-r", "60", "-f", str(page), "-l", str(page), str(pdf), str(stem)],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    ppm = next(workdir.glob("raster-%s*.ppm" % pdf.stem))
    data = ppm.read_bytes()
    fields, i = [], 0
    while len(fields) < 4:  # magic, width, height, maxval
        while data[i:i + 1].isspace():
            i += 1
        j = i
        while not data[j:j + 1].isspace():
            j += 1
        fields.append(data[i:j])
        i = j
    i += 1
    assert fields[0] == b"P6", "expected a binary PPM, got %r" % fields[0]
    width, height = int(fields[1]), int(fields[2])
    px = data[i:i + width * height * 3]
    chromatic = 0
    for k in range(0, len(px), 3):
        r, g, b = px[k], px[k + 1], px[k + 2]
        if max(r, g, b) - min(r, g, b) > threshold:
            chromatic += 1
    return chromatic, width * height


# --------------------------------------------------------------------------- #
# 1. structure
# --------------------------------------------------------------------------- #

def test_shipped_reference_structure():
    assert SHIPPED.exists(), "the CV phase requires %s to ship with the skill" % SHIPPED.relative_to(ROOT)
    _assert_structure(mk.inspect(SHIPPED), "shipped reference.docx")


def test_regenerated_reference_structure():
    """The regeneration path must work with the pandoc that is actually installed.

    pandoc <= 3.1 ships a self-closing <w:sectPr />; later versions ship a
    populated one. The script used to handle only the second, leaving pgMar
    outside sectPr -- silently ignored, one-inch margins, three pages.
    """
    _need("pandoc")
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / "reference.docx"
        assert mk.main(["--out", str(out)]) == 0
        _assert_structure(mk.inspect(out), "regenerated reference.docx")


def test_sect_pr_rewrite_handles_every_shape():
    """Pure-string check of the sectPr rewrite, independent of pandoc's version."""
    body = '<w:body><w:p/>%s</w:body>'
    shapes = {
        "self-closing": '<w:sectPr />',
        "self-closing, no space": '<w:sectPr/>',
        "empty pair": '<w:sectPr></w:sectPr>',
        "populated": '<w:sectPr><w:footnotePr><w:numRestart w:val="eachSect"/></w:footnotePr></w:sectPr>',
        "populated, stale pgMar": '<w:sectPr><w:pgMar w:top="1440"/><w:footnotePr/></w:sectPr>',
        "type + docGrid": '<w:sectPr><w:type w:val="continuous"/><w:docGrid w:linePitch="360"/></w:sectPr>',
        "absent": '',
    }
    for label, sect in shapes.items():
        out = mk.force_sect_pr(body % sect, "a4")
        m = re.search(r"<w:sectPr\b[^>]*>(.*?)</w:sectPr>", out, re.S)
        assert m, "%s: no sectPr pair in output" % label
        inner = m.group(1)
        assert inner.count("<w:pgMar") == 1 and out.count("<w:pgMar") == 1, "%s: pgMar not exactly once inside sectPr" % label
        assert inner.count("<w:pgSz") == 1, "%s: pgSz not exactly once inside sectPr" % label
        assert 'w:top="720"' in inner, "%s: stale margin survived" % label
        assert inner.index("<w:pgSz") < inner.index("<w:pgMar"), "%s: pgSz must precede pgMar" % label
        if "<w:type" in inner:
            assert inner.index("<w:type") < inner.index("<w:pgSz") < inner.index("<w:docGrid"), \
                "%s: schema order type < pgSz/pgMar < docGrid broken" % label


def test_style_rewrite_never_duplicates_sizes():
    """force_rpr / force_doc_defaults replace sizes, never stack a second w:sz."""
    with_size = '<w:style w:styleId="X"><w:name w:val="X"/><w:rPr><w:sz w:val="24" /><w:szCs w:val="24" /></w:rPr></w:style>'
    bare = '<w:style w:styleId="X"><w:name w:val="X"/><w:qFormat/></w:style>'
    for block in (with_size, bare):
        out = mk.force_spacing(mk.force_rpr(block, 20), 0, 60)
        assert re.findall(r'<w:sz w:val="(\d+)"', out) == ["20"], out
        assert out.count("<w:pPr>") == 1 and out.count("<w:spacing") == 1, out
        assert out.index("<w:pPr>") < out.index("<w:rPr>"), "pPr must precede rPr: %s" % out
    defaults = '<w:docDefaults><w:rPrDefault><w:rPr><w:sz w:val="24" /><w:szCs w:val="24" /></w:rPr></w:rPrDefault></w:docDefaults>'
    out = mk.force_doc_defaults(defaults, 20)
    assert re.findall(r'<w:sz w:val="(\d+)"', out) == ["20"], out


def test_colour_is_stripped_from_every_style():
    """Harvard style is black and white; pandoc's default is not."""
    styles = (
        '<w:styles><w:style w:styleId="Heading1"><w:rPr>'
        '<w:color w:val="0F4761"/><w:b/></w:rPr></w:style>'
        '<w:style w:styleId="Hyperlink"><w:rPr>'
        '<w:color w:val="4F81BD" w:themeColor="hyperlink"/><w:u w:val="single"/>'
        '</w:rPr></w:style></w:styles>'
    )
    out = mk.strip_colour(styles)
    assert "<w:color" not in out, out
    assert "<w:b/>" in out and '<w:u w:val="single"/>' in out, \
        "weights and underlines must survive: %s" % out


# --------------------------------------------------------------------------- #
# 2. render
# --------------------------------------------------------------------------- #

def test_fixture_renders_on_two_pages_with_shipped_reference():
    _need("pandoc", "libreoffice", "pdfinfo", "pdftotext")
    with tempfile.TemporaryDirectory() as tmp:
        r = _render(FIXTURE, pathlib.Path(tmp), SHIPPED)
        assert r["pages"] <= MAX_PAGES, "fixture CV rendered on %d pages with the shipped reference (gate: <= %d)" % (r["pages"], MAX_PAGES)
        assert len(r["text"]) >= MIN_TEXT_CHARS, "PDF yields only %d characters -- is it an image?" % len(r["text"])
        for needle in MUST_SURVIVE:
            assert needle in r["text"], "%r did not survive into the PDF text" % needle
        assert r["left_margin_pt"] is not None and r["left_margin_pt"] < HALF_INCH_PT + 4, \
            "left margin measured at %.1fpt; expected ~%.0fpt (half an inch)" % (r["left_margin_pt"], HALF_INCH_PT)


def test_shipped_reference_renders_black_and_white():
    """Phase 2 promises the Harvard style: black and white. Measure it on the page."""
    _need("pandoc", "libreoffice", "pdfinfo", "pdftotext", "pdftoppm")
    with tempfile.TemporaryDirectory() as tmp:
        work = pathlib.Path(tmp)
        r = _render(FIXTURE, work, SHIPPED)
        chromatic, total = _chromatic_pixels(r["pdf"], work)
        assert chromatic == 0, \
            "page 1 has %d chromatic pixels of %d (%.2f%%): something on the page is not black, white or grey" % (
                chromatic, total, 100.0 * chromatic / total)


def test_stock_pandoc_styling_does_not_fit_control():
    """If this ever passes on two pages, the fixture is too short to prove anything."""
    _need("pandoc", "libreoffice", "pdfinfo", "pdftotext", "pdftoppm")
    with tempfile.TemporaryDirectory() as tmp:
        work = pathlib.Path(tmp)
        r = _render(FIXTURE, work, None)
        assert r["left_margin_pt"] is not None and r["left_margin_pt"] > 60, \
            "stock pandoc should render one-inch margins, measured %.1fpt" % r["left_margin_pt"]
        assert r["pages"] > MAX_PAGES, \
            "stock pandoc styling fit the fixture on %d pages: the fixture no longer exercises the reference document" % r["pages"]
        chromatic, _ = _chromatic_pixels(r["pdf"], work)
        assert chromatic > 0, \
            "stock pandoc should paint headings blue; if it no longer does, the black-and-white test proves nothing"


# --------------------------------------------------------------------------- #
# runner (no pytest required)
# --------------------------------------------------------------------------- #

def _main() -> int:
    tests = [(n, f) for n, f in sorted(globals().items()) if n.startswith("test_") and callable(f)]
    failed = 0
    for name, fn in tests:
        try:
            fn()
        except unittest.SkipTest as e:
            print("SKIP  %s  (%s)" % (name, e))
        except Exception:
            failed += 1
            print("FAIL  %s" % name)
            traceback.print_exc()
        else:
            print("ok    %s" % name)
    print("\n%d test(s), %d failed" % (len(tests), failed))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(_main())
